version: '3'
services:
#  studygolang:
#    container_name: learnue
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 80:8088
#    networks:
#      - learnue_net
#    links:
#      - redis:redis
#      - mysql:mysql
#    volumes:
#      - ./static:/app/studygolang/static
#      - ./template:/app/studygolang/template
#      - ./log:/app/studygolang/log
  mysql:
    image: mysql:8
    container_name: learnue_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MysqlRootPassword}
      MYSQL_USER: ${MysqlUser}
      MYSQL_PASSWORD: ${MysqlPassword}
      MYSQL_DATABASE: ${MysqlDatabase}
    volumes:
      - ./mysql_data:/var/lib/mysql
  redis:
    image: redis:5-alpine
    container_name: learnue_redis
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6380:6379"
    command: redis-server
#  es:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
#    container_name: learnue_es
#    environment:
#      - discovery.type=single-node
#    volumes:
#      - ./data/es:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200

